public class UpdateSubEstController extends BaseEstimateController{
    
    public override void createURL(Map<String,String> params){
    
    }
    
    
    public UpdateSubEstController(UpdateSubUrlBuilder ub){
            super(ub);
    }
    
    public UpdateSubEstController(UrlBuilder ub){
            super(ub);
    }
    
    public UpdateSubEstController(){
        super();
    }
    
    

}